// Code generated by MockGen. DO NOT EDIT.
// Source: memory-service.go

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockMemoryService is a mock of MemoryService interface
type MockMemoryService struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryServiceMockRecorder
}

// MockMemoryServiceMockRecorder is the mock recorder for MockMemoryService
type MockMemoryServiceMockRecorder struct {
	mock *MockMemoryService
}

// NewMockMemoryService creates a new mock instance
func NewMockMemoryService(ctrl *gomock.Controller) *MockMemoryService {
	mock := &MockMemoryService{ctrl: ctrl}
	mock.recorder = &MockMemoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMemoryService) EXPECT() *MockMemoryServiceMockRecorder {
	return m.recorder
}

// InMemGetPOST mocks base method
func (m *MockMemoryService) InMemGetPOST(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InMemGetPOST", w, r)
}

// InMemGetPOST indicates an expected call of InMemGetPOST
func (mr *MockMemoryServiceMockRecorder) InMemGetPOST(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InMemGetPOST", reflect.TypeOf((*MockMemoryService)(nil).InMemGetPOST), w, r)
}

// Get mocks base method
func (m *MockMemoryService) Get(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", w, r)
}

// Get indicates an expected call of Get
func (mr *MockMemoryServiceMockRecorder) Get(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMemoryService)(nil).Get), w, r)
}

// GetDataByKey mocks base method
func (m *MockMemoryService) GetDataByKey(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetDataByKey", w, r)
}

// GetDataByKey indicates an expected call of GetDataByKey
func (mr *MockMemoryServiceMockRecorder) GetDataByKey(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByKey", reflect.TypeOf((*MockMemoryService)(nil).GetDataByKey), w, r)
}
